//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSystem.DBInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class semester
    {
        public semester()
        {
            this.rounds = new HashSet<round>();
        }
    
        public int id { get; set; }
        public string year { get; set; }
        public byte semesterNumber { get; set; }
        public byte numberOfWeeks { get; set; }
    
        public virtual ICollection<round> rounds { get; set; }
    }
}
