//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSystem.DBInterface
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimetablingSystemContext : DbContext
    {
        public TimetablingSystemContext()
            : base("name=TimetablingSystemContext")
        {
            //Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<building> buildings { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<facility> facilities { get; set; }
        public DbSet<module> modules { get; set; }
        public DbSet<request> requests { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<round> rounds { get; set; }
        public DbSet<semester> semesters { get; set; }
    }
}
